alias cat="bat --style=plain"
alias ls="eza"
alias tree="eza -T"
alias abbr="abbrev-alias"

abbr up="cd .."
abbr d="docker"
abbr -r dcp="d compose"
abbr -r dc="d container"
abbr gc="git commit"
abbr gs="git status"
abbr ggl="google"
